version: '3.1'

services:
  app:
      build:
          context: .
      entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index.js
      networks: 
          - node-network
      # volumes: 
      #     - ./node:/usr/src/app
      tty: true
      container_name: app
      # ports: 
      #     - 3000:3000
      depends_on: 
            - db
  nginx:
        image: nginx:latest
        volumes:
          - ./.docker/nginx/node.conf:/etc/nginx/conf.d/node.template
        ports:
          - '8080:80'
        command: 'bash -c "cat /etc/nginx/conf.d/node.template > /etc/nginx/conf.d/default.conf && nginx -g ''daemon off;''"'
        networks: 
                - node-network

  db:
        platform: linux/x86_64
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        volumes: 
            - ./.docker/mysql:/var/lib/mysql
        environment: 
            - MYSQL_DATABASE=nodedb
            - MYSQL_ROOT_PASSWORD=root
        networks: 
            - node-network

networks: 
    node-network:
        driver: bridge